kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: postgresql
  labels:
    app: etherpad_db
parameters:
- name: NAME
  description: Name of the DC, service, route
  required: true
  value: etherpad
- name: ADMIN_PASSWORD
  description: Admin password for etherpad/admin
  required: true
- name: DB_TYPE
  description: Database Type (postgres, mysql)
  value: postgres
  required: true
- name: DB_HOST
  description: Database host
  value: postgresql
  required: true
- name: DB_PORT
  description: Database Port
  value: "5432"
  required: true
- name: DB_DATABASE
  description: Database Name
  value: ether
  required: true
- name: DB_USER
  description: Database User ID
  value: ether
  required: true
- name: DB_PASS
  description: Database Password
  value: ether
  required: true
- name: ETHERPAD_IMAGE
  description: Etherpad Image to be used
  value: "quay.io/gpte-devops-automation/etherpad:latest"
  required: true
spec:
  strategy:
    type: Recreate
  selector:
    name: postgresql
  template:
    metadata:
      labels:
        name: postgresql
    spec:
      containers:
        - resources:
            limits:
              memory: 512Mi
          name: postgresql
          image: postgresql:10
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: database-name
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pv-claim
