---
kind: Service
apiVersion: v1
metadata:
  name: postgresql
  creationTimestamp: null
  labels:
    app: etherpad_db
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: postgresql
status:
  loadBalancer: {}
