---
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: etherpad_db
  name: postgresql-secret
data:
  database-name: ZXRoZXJwYWQ=
  database-password: ZXRoZXI=
  database-user: ZXRoZXI=
type: Opaque
