--
apiVersion: v1
data:
  database-name: ZXRoZXJwYWQ=
  database-password: ZXRoZXI=
  database-user: ZXRoZXI=
kind: Secret
metadata:
  labels:
    app: etherpad_db
  name: postgresql-secret
type: Opaque
